name: cardio-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - bwa=0.7.19
  - samtools=1.20
  - bcftools=1.20
  - gatk4=4.5.0.0
  - snpeff=5.2
  - snpsift=5.2
  - fastp=0.23.*
  - fastqc=0.12.*
  - dwgsim=0.1.13
  - htslib=1.20
  - tabix
  - jq
  - pip
  - pip:
      - pandas
      - jinja2
